import type {
  HeroPoseAdditiveMap,
  HeroPoseDefinition,
  HeroPoseMap,
  HeroVisualState,
} from './AnimationStateTypes';

const deg = (value: number): number => (value * Math.PI) / 180;

const idlePose: HeroPoseDefinition = {
  bodyRotation: [0, 0, 0],
  torsoOffset: [0, 0, 0],
  torsoRotation: [deg(-3), deg(5), deg(1)],
  weaponAnchorPosition: [0.32, 1.24, 0.08],
  weaponAnchorRotation: [deg(4), deg(8), deg(28)],
  swordPivotPosition: [0.12, 0.1, 0.08],
  swordPivotRotation: [deg(-8), deg(18), deg(50)],
};

const statePoses: Partial<Record<HeroVisualState, HeroPoseMap>> = {
  swing: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, -0.01, -0.03],
      torsoRotation: [deg(-8), deg(12), deg(-2)],
      weaponAnchorPosition: [0.36, 1.23, 0.04],
      weaponAnchorRotation: [deg(6), deg(14), deg(26)],
      swordPivotPosition: [0.2, 0.1, -0.04],
      swordPivotRotation: [deg(-10), deg(34), deg(58)],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.02, 0.08],
      torsoRotation: [deg(0), deg(-12), deg(3)],
      weaponAnchorPosition: [0.16, 1.22, 0.12],
      weaponAnchorRotation: [deg(-2), deg(-12), deg(8)],
      swordPivotPosition: [-0.28, 0.12, 0.16],
      swordPivotRotation: [deg(-6), deg(-44), deg(-44)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0, 0.02],
      torsoRotation: [deg(0), deg(-2), deg(1)],
      weaponAnchorPosition: [0.28, 1.23, 0.08],
      weaponAnchorRotation: [deg(2), deg(8), deg(22)],
      swordPivotPosition: [0.08, 0.1, 0.06],
      swordPivotRotation: [deg(-8), deg(16), deg(38)],
    },
  },
  thrustCharge: {
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.02, -0.1],
      torsoRotation: [deg(-20), deg(16), deg(-10)],
      weaponAnchorPosition: [0.46, 1.3, -0.06],
      weaponAnchorRotation: [deg(16), deg(14), deg(32)],
      swordPivotPosition: [0.12, 0.18, -0.04],
      swordPivotRotation: [deg(-26), deg(18), deg(86)],
    },
  },
  thrustRelease: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, -0.04],
      torsoRotation: [deg(-10), deg(10), deg(-8)],
      weaponAnchorPosition: [0.42, 1.28, -0.02],
      weaponAnchorRotation: [deg(10), deg(12), deg(28)],
      swordPivotPosition: [0.1, 0.18, 0.02],
      swordPivotRotation: [deg(-20), deg(16), deg(82)],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.06, 0.16],
      torsoRotation: [deg(22), deg(-18), deg(14)],
      weaponAnchorPosition: [0.22, 1.2, 0.18],
      weaponAnchorRotation: [deg(-8), deg(-8), deg(4)],
      swordPivotPosition: [-0.08, 0.08, 0.28],
      swordPivotRotation: [deg(28), deg(-24), deg(-76)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, 0],
      torsoRotation: [deg(0), deg(2), deg(2)],
      weaponAnchorPosition: [0.3, 1.18, 0.12],
      weaponAnchorRotation: [deg(-2), deg(2), deg(12)],
      swordPivotPosition: [-0.02, 0.06, 0.16],
      swordPivotRotation: [deg(10), deg(-8), deg(-30)],
    },
  },
  fireBurst: {
    active: {
      bodyRotation: [deg(6), 0, 0],
      torsoOffset: [0, 0.04, 0.08],
      torsoRotation: [deg(18), deg(-4), deg(14)],
      weaponAnchorPosition: [0.2, 1.1, -0.04],
      weaponAnchorRotation: [deg(-20), deg(16), deg(22)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-8), deg(0), deg(0)],
    },
  },
  fireVault: {
    startup: {
      bodyRotation: [deg(5), 0, 0],
      torsoOffset: [0, -0.02, -0.12],
      torsoRotation: [deg(-24), deg(18), deg(-10)],
      weaponAnchorPosition: [0.36, 1.18, -0.26],
      weaponAnchorRotation: [deg(78), deg(24), deg(16)],
      swordPivotPosition: [0.02, 0.01, -0.02],
      swordPivotRotation: [deg(-10), deg(16), deg(-8)],
    },
    travel: {
      bodyRotation: [deg(-14), 0, 0],
      torsoOffset: [0, 0.16, -0.2],
      torsoRotation: [deg(-38), deg(24), deg(-14)],
      weaponAnchorPosition: [0.18, 1.8, -0.28],
      weaponAnchorRotation: [deg(132), deg(22), deg(10)],
      swordPivotPosition: [0.05, 0.04, -0.03],
      swordPivotRotation: [deg(20), deg(22), deg(-20)],
    },
    impact: {
      bodyRotation: [deg(14), 0, 0],
      torsoOffset: [0, 0.01, 0.22],
      torsoRotation: [deg(40), deg(-12), deg(14)],
      weaponAnchorPosition: [0.04, 0.54, 0.72],
      weaponAnchorRotation: [deg(-126), deg(-20), deg(14)],
      swordPivotPosition: [0, -0.04, 0.05],
      swordPivotRotation: [deg(-30), deg(-10), deg(12)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, 0.06],
      torsoRotation: [deg(10), deg(-4), deg(6)],
      weaponAnchorPosition: [0.18, 0.96, 0.24],
      weaponAnchorRotation: [deg(-40), deg(-10), deg(14)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-10), deg(0), deg(2)],
    },
  },
  fireWheel: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, -0.04],
      torsoRotation: [deg(-10), deg(10), deg(-8)],
      weaponAnchorPosition: [0.44, 1.1, -0.04],
      weaponAnchorRotation: [deg(-12), deg(10), deg(14)],
      swordPivotPosition: [0.01, 0.02, 0],
      swordPivotRotation: [deg(-8), deg(4), deg(6)],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.08, 0.1],
      torsoRotation: [deg(18), deg(0), deg(2)],
      weaponAnchorPosition: [0.36, 1.22, 0.08],
      weaponAnchorRotation: [deg(8), deg(4), deg(30)],
      swordPivotPosition: [0.02, 0.03, 0.02],
      swordPivotRotation: [deg(-16), deg(8), deg(18)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.03, 0.04],
      torsoRotation: [deg(8), deg(0), deg(2)],
      weaponAnchorPosition: [0.34, 1.12, 0.16],
      weaponAnchorRotation: [deg(-8), deg(0), deg(18)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-10), deg(4), deg(8)],
    },
  },
  dragonFireCast: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.02, -0.04],
      torsoRotation: [deg(-14), deg(20), deg(-10)],
      weaponAnchorPosition: [0.24, 1.28, -0.1],
      weaponAnchorRotation: [deg(40), deg(20), deg(8)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(0), deg(0), deg(0)],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.06, 0.12],
      torsoRotation: [deg(16), deg(-14), deg(14)],
      weaponAnchorPosition: [0.34, 1.0, 0.36],
      weaponAnchorRotation: [deg(-36), deg(-14), deg(22)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(0), deg(0), deg(0)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, 0],
      torsoRotation: [deg(-1), deg(2), deg(3)],
      weaponAnchorPosition: [0.32, 1.06, 0.08],
      weaponAnchorRotation: [deg(-20), deg(-8), deg(16)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-4), deg(0), deg(0)],
    },
  },
};

const timelineAdditives: Partial<Record<HeroVisualState, HeroPoseAdditiveMap>> = {
  swing: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0, 0],
      torsoRotation: [0, deg(3), deg(-1)],
      weaponAnchorPosition: [0.01, 0, 0],
      weaponAnchorRotation: [0, deg(2), 0],
      swordPivotPosition: [0.02, 0, 0],
      swordPivotRotation: [0, deg(4), deg(4)],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, 0.04],
      torsoRotation: [0, deg(-6), deg(2)],
      weaponAnchorPosition: [0, 0, 0.02],
      weaponAnchorRotation: [0, deg(-4), 0],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [0, deg(-10), deg(-14)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0, 0],
      torsoRotation: [0, 0, 0],
      weaponAnchorPosition: [0, 0, 0.01],
      weaponAnchorRotation: [0, deg(2), 0],
      swordPivotPosition: [0.02, 0, 0.01],
      swordPivotRotation: [0, deg(6), deg(8)],
    },
  },
  thrustRelease: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0, 0],
      torsoRotation: [0, 0, 0],
      weaponAnchorPosition: [0, 0.04, -0.06],
      weaponAnchorRotation: [deg(8), 0, 0],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [0, 0, 0],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0, 0.04],
      torsoRotation: [0, 0, 0],
      weaponAnchorPosition: [0, -0.06, 0.18],
      weaponAnchorRotation: [deg(-14), 0, 0],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [0, 0, 0],
    },
  },
  fireVault: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, -0.01, -0.06],
      torsoRotation: [deg(-6), deg(8), deg(-4)],
      weaponAnchorPosition: [0.08, 0.04, -0.12],
      weaponAnchorRotation: [deg(12), deg(8), 0],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-6), deg(4), deg(-6)],
    },
    travel: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.04, -0.04],
      torsoRotation: [deg(-8), deg(4), deg(-4)],
      weaponAnchorPosition: [0, 0.12, -0.06],
      weaponAnchorRotation: [deg(18), deg(4), 0],
      swordPivotPosition: [0, 0.01, 0],
      swordPivotRotation: [deg(8), deg(6), deg(-8)],
    },
    impact: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.02, 0.1],
      torsoRotation: [deg(10), 0, deg(2)],
      weaponAnchorPosition: [0, -0.14, 0.16],
      weaponAnchorRotation: [deg(-30), 0, 0],
      swordPivotPosition: [0, -0.01, 0.02],
      swordPivotRotation: [deg(-12), 0, deg(8)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0, 0.04],
      torsoRotation: [deg(4), 0, 0],
      weaponAnchorPosition: [0, -0.04, 0.08],
      weaponAnchorRotation: [deg(-10), 0, 0],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-6), 0, deg(4)],
    },
  },
  fireWheel: {
    startup: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, -0.02],
      torsoRotation: [deg(-4), 0, deg(-2)],
      weaponAnchorPosition: [0.06, 0.04, -0.06],
      weaponAnchorRotation: [deg(-2), 0, deg(6)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-4), 0, deg(6)],
    },
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.04, 0.08],
      torsoRotation: [deg(8), 0, 0],
      weaponAnchorPosition: [0.02, 0.08, 0.08],
      weaponAnchorRotation: [deg(6), 0, deg(12)],
      swordPivotPosition: [0.02, 0.02, 0],
      swordPivotRotation: [deg(-8), deg(4), deg(14)],
    },
    recovery: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.02, 0.03],
      torsoRotation: [deg(4), 0, 0],
      weaponAnchorPosition: [0.02, 0.03, 0.04],
      weaponAnchorRotation: [deg(2), 0, deg(8)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(-4), 0, deg(4)],
    },
  },
  dragonFireCast: {
    active: {
      bodyRotation: [0, 0, 0],
      torsoOffset: [0, 0.01, 0.04],
      torsoRotation: [0, deg(-8), 0],
      weaponAnchorPosition: [0.04, -0.02, 0.08],
      weaponAnchorRotation: [deg(-8), 0, 0],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [0, 0, 0],
    },
  },
};

export const heroPoseConfig = {
  weaponMountOffset: [0.1, 0, -0.01] as [number, number, number],
  blend: {
    locomotionSharpness: 11,
    fastMoveSharpness: 14,
    bodySharpness: 20,
    torsoSharpness: 25,
    weaponSharpness: 38,
  },
  locomotion: {
    fastMoveThreshold: 0.64,
    visualLiftAmplitude: 0.04,
    attackLocomotionScale: 0.03,
    attackIdleScale: 0.02,
    stride: {
      baseRate: 0.75,
      speedRate: 4.25,
      strafeRateScale: 0.82,
    },
    readyBias: {
      torsoYawTowardCamera: deg(8),
      weaponForwardLift: 0.1,
      weaponForwardReach: 0.12,
    },
    idleSway: {
      frequency: 1.45,
      weaponAnchorPosition: [0.004, 0.008, 0.006] as [number, number, number],
      weaponAnchorRotation: [deg(0.6), deg(0.6), deg(0.75)] as [number, number, number],
      swordPivotRotation: [deg(0.8), deg(0.7), deg(0.85)] as [number, number, number],
      torsoRotation: [deg(0.5), deg(0.4), deg(0.3)] as [number, number, number],
    },
    runBob: {
      frequency: 6.6,
      weaponAnchorPosition: [0.015, 0.022, 0.016] as [number, number, number],
      weaponAnchorRotation: [deg(3.2), deg(1.8), deg(2.8)] as [number, number, number],
      swordPivotRotation: [deg(4.5), deg(2.2), deg(3.4)] as [number, number, number],
      torsoRotation: [deg(2.8), deg(1.8), deg(2.2)] as [number, number, number],
    },
    lean: {
      bodyRollFromStrafe: deg(6),
      bodyPitchFromForward: deg(3.5),
      torsoYawFromStrafe: deg(6),
      torsoRollFromStrafe: deg(5),
      torsoPitchFromForward: deg(4),
    },
    attackLean: {
      torsoRoll: deg(6),
      torsoPitchFromCharge: deg(7),
    },
    headTurnScale: 0.35,
  },
  glow: {
    base: 0.24,
    actionTintScale: 0.66,
    chargeScale: 0.28,
    hitConfirmScale: 0.22,
  },
  locomotionPoses: {
    idle: idlePose,
    run: {
      bodyRotation: [deg(-2), 0, 0],
      torsoOffset: [0, 0.03, 0.01],
      torsoRotation: [deg(-6), deg(8), deg(6)],
      weaponAnchorPosition: [0.48, 1.18, 0.06],
      weaponAnchorRotation: [deg(-10), deg(2), deg(40)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(8), deg(8), deg(-12)],
    } satisfies HeroPoseDefinition,
    fastMove: {
      bodyRotation: [deg(-4), 0, 0],
      torsoOffset: [0, 0.04, 0.03],
      torsoRotation: [deg(-12), deg(12), deg(10)],
      weaponAnchorPosition: [0.44, 1.14, 0.12],
      weaponAnchorRotation: [deg(-12), deg(4), deg(44)],
      swordPivotPosition: [0, 0, 0],
      swordPivotRotation: [deg(10), deg(10), deg(-10)],
    } satisfies HeroPoseDefinition,
  },
  actionCurves: {
    swing: {
      drawBackYaw: deg(12),
      drawBackReach: 0.06,
      sweepYaw: deg(76),
      sweepRoll: deg(20),
      sweepReach: 0.16,
      lateralSweep: 0.34,
      frontOffset: 0.1,
      arcLift: 0.08,
      torsoYaw: deg(8),
      torsoRoll: deg(2),
    },
    thrustCharge: {
      pullBack: 0.12,
      lift: 0.28,
      gripLift: 0.12,
      tipAimYaw: deg(12),
      torsoPitch: deg(12),
    },
    thrustRelease: {
      extension: 0.34,
      recoil: 0.22,
      torsoPitch: deg(20),
    },
    fireBurst: {
      trail: 0.22,
      braceRoll: deg(16),
    },
    fireVault: {
      startupCrouch: 0.18,
      startupCoilYaw: deg(18),
      travelRaise: 0.48,
      travelYaw: deg(28),
      overheadPitch: deg(42),
      slamDrop: 0.62,
      slamPitch: deg(42),
      slamReach: 0.24,
      recoveryLift: 0.12,
    },
    fireWheel: {
      bracePull: 0.08,
      chestLift: 0.24,
      roarLeanBack: deg(20),
      swordLift: 0.18,
      swordRoll: deg(24),
      recoverySettle: 0.12,
    },
    dragonFireCast: {
      raise: 0.22,
      braceForward: 0.28,
      castPitch: deg(22),
    },
  },
  statePoses,
  timelineAdditives,
};
