export const combatConfig = {
  dummy: {
    maxHealth: 100,
    radius: 0.85,
    respawnDelay: 4,
  },
  healing: {
    radius: 1.85,
    healPerSecond: 52,
    cleanseFire: true,
  },
  camera: {
    normalDistance: 7.7,
    combatDistance: 7.2,
    shoulderOffset: 1.35,
    targetShoulderOffset: 0.34,
    focusHeight: 1.8,
    normalPositionSharpness: 16,
    combatPositionSharpness: 20,
    normalTargetSharpness: 18,
    combatTargetSharpness: 23,
    lookAheadDistance: 0.65,
    attackLookAheadDistance: 1.1,
    pitchMin: -0.65,
    pitchMax: 0.5,
    aimBiasSharpness: 10,
    shakeDamping: 18,
  },
  movement: {
    forwardMoveSpeed: 16.8,
    strafeMoveSpeed: 15.8,
    acceleration: 132,
    deceleration: 224,
    reverseAcceleration: 286,
    strafeAccelerationMultiplier: 1.95,
    airControl: 0.76,
    gravity: 28,
    jumpSpeed: 8.8,
    turnSharpness: 58,
    aimTurnSharpness: 64,
    attackTurnSharpness: 64,
    movementSmoothing: 52,
    externalVelocityDrag: 11,
    attackDriveSharpness: 0.3,
    burstDriveSharpness: 0.92,
    stopSpeedEpsilon: 0.12,
  },
  momentumTech: {
    retentionPercent: 0.6,
    jumpWindowDuration: 0.16,
    boostedJumpHorizontalMultiplier: 1.14,
    boostedJumpVerticalBonus: 0.2,
    maxCarrySpeedCap: 13,
    momentumDecayRate: 4.2,
    minimumCarrySpeed: 4.2,
  },
  dash: {
    cooldown: 0.48,
    speed: 53,
    duration: 0.11,
    distance: 5.8,
    airDashCount: 1,
    downwardDashMultiplier: 1.45,
    shake: 0.05,
  },
  bow: {
    damage: {
      head: 100,
      body: 50,
    },
    charge: {
      minimumDrawTime: 0.25,
      fullChargeTime: 0.8,
      movementSpeedMultiplier: 0.88,
    },
    arrow: {
      gravityBase: 18,
      radius: 0.16,
      fireInterval: 0.17,
      minimumSpreadRadians: 0.02,
      fullSpreadRadians: 0.0012,
      minimum: {
        speed: 62,
        gravityMultiplier: 1.02,
        lifetime: 1.2,
      },
      mid: {
        speed: 92,
        gravityMultiplier: 0.8,
        lifetime: 1.48,
      },
      full: {
        speed: 124,
        gravityMultiplier: 0.62,
        lifetime: 1.82,
      },
    },
  },
  launch: {
    cooldown: 1.9,
    upwardSpeed: 12.2,
    forwardSpeed: 5.8,
    slowFallGravityScale: 0.36,
    slowFallDuration: 0.82,
    slowFallAirControl: 1.1,
    shake: 0.12,
  },
  shield: {
    cooldown: 4.2,
    duration: 1.8,
    radius: 1.08,
    hitFlashSeconds: 0.2,
  },
  assist: {
    range: 3.9,
    snapDistance: 0.9,
    thrustSnapDistance: 1.15,
    swingArcRadians: 1.86,
    wheelArcRadians: 2.35,
    thrustArcRadians: 0.52,
    facingAssistSharpness: 46,
  },
  feedback: {
    hitFlashSeconds: 0.16,
    hitPauseSeconds: 0.04,
    hitConfirmSeconds: 0.18,
    heavyShake: 0.18,
    lightShake: 0.09,
    dummyHitOffset: 0.2,
    dummyHitTilt: 0.28,
    dummySettleSharpness: 20,
    abilityFlashColors: {
      arrow: 0xffe6bf,
      headshot: 0xff7c52,
      shield: 0x8ed6ff,
      swing: 0xffd9ad,
      thrust: 0xfff0a8,
      burst: 0xffb76e,
      vault: 0xff8559,
      wheel: 0xff9a57,
      dragon: 0xff5a36,
    },
    abilityPulseScales: {
      arrow: 0.9,
      headshot: 1.3,
      shield: 1.1,
      swing: 1,
      thrust: 1.08,
      burst: 1.15,
      vault: 1.45,
      wheel: 1.3,
      dragon: 1.65,
    },
  },
  burn: {
    tickRate: 0.25,
  },
  abilities: {
    swing: {
      cooldown: 0.4,
      startup: 0.09,
      active: 0.19,
      recovery: 0.17,
      damage: 32,
      range: 2.9,
      radius: 1.28,
      lungeSpeed: 3.9,
      moveScale: 0.42,
    },
    thrust: {
      cooldown: 1.55,
      minCharge: 0.16,
      maxCharge: 0.9,
      startup: 0.11,
      active: 0.13,
      recovery: 0.26,
      minDamage: 52,
      maxDamage: 96,
      range: 3.8,
      radius: 0.82,
      lungeSpeed: 7.6,
      moveScale: 0.14,
      slowDuration: 0.95,
      slowAmount: 0.42,
    },
    burst: {
      cooldown: 4.1,
      duration: 0.12,
      distance: 5.6,
      damage: 12,
      moveScale: 0,
    },
    vault: {
      cooldown: 7.4,
      startup: 0.14,
      travel: 0.3,
      impact: 0.11,
      recovery: 0.24,
      distance: 2.25,
      startupLift: 0.46,
      visualLift: 2.3,
      slamVisualDrop: 0.36,
      damage: 65,
      radius: 2.35,
      stunDuration: 0.75,
      moveScale: 0.15,
    },
    wheel: {
      cooldown: 5.4,
      startup: 0.12,
      active: 0.18,
      recovery: 0.22,
      damage: 34,
      range: 3.35,
      radius: 3.35,
      lungeSpeed: 0,
      burnDamagePerSecond: 12,
      burnDuration: 2.5,
      slowDuration: 1.1,
      slowAmount: 0.34,
      zoneDuration: 3.4,
      moveScale: 0.18,
    },
    dragon: {
      cooldown: 11.5,
      startup: 0.18,
      active: 0.12,
      recovery: 0.26,
      damage: 100,
      speed: 16,
      radius: 1.6,
      life: 1.25,
      burnDamagePerSecond: 9,
      burnDuration: 9,
      moveScale: 0.35,
    },
  },
} as const;

export type AbilityId = keyof typeof combatConfig.abilities;
